### ISSUE TITLE
Incluir Logout

### ISSUE THREAD

**Issue by leticia-pontes** [leticia-pontes/eng-software-3bcc#43]
## Objetivo
Possibilitar o Logout pelo usuário.

**Comment by faresbouzayen** [comment]
Hi @leticia-pontes,

I'd like to help with this! I'll implement the logout functionality allowing users to securely end their session and be redirected to the login page. Will the logout be token-based or session-based?

Thanks!

**Comment by leticia-pontes** [comment]
Hey @faresbouzayen,
I was thinking about session-based. I'd really appreciate the help!
